{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "a07e37d1-2f57-424c-a099-6539070761bf",
   "metadata": {},
   "outputs": [],
   "source": [
    "import requests\n",
    "import re\n",
    "from bs4 import BeautifulSoup\n",
    "import json\n",
    "import html2text"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "aa1a167f-4e0b-4dc8-a393-ef9c3bd6b157",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Markdown content extracted and stored in markdown_data.json\n"
     ]
    }
   ],
   "source": [
    "base_url = \"https://sigstore.github.io/sigstore-python/sigstore/\"\n",
    "subpaths = [\"errors.html\", \"oidc.html\", \"sign.html\", \"transparency.html\", \"verify.html\"]\n",
    "data = {}\n",
    "\n",
    "for subpath in subpaths:\n",
    "    url = f\"{base_url}{subpath}\"\n",
    "    response = requests.get(url)\n",
    "    if response.status_code == 200:\n",
    "        html_content = response.text\n",
    "        soup = BeautifulSoup(html_content, 'html.parser')\n",
    "\n",
    "        for tag in soup.find_all(['img', 'svg', 'style']):\n",
    "            tag.decompose()\n",
    "\n",
    "        markdown_content = html2text.html2text(str(soup))\n",
    "        \n",
    "        key = subpath.split('.')[0]\n",
    "        data[key] = markdown_content\n",
    "\n",
    "with open('../../data/raw/markdown_data.json', 'w') as json_file:\n",
    "    json.dump(data, json_file, indent=4)\n",
    "\n",
    "print(\"Markdown content extracted and stored in markdown_data.json\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "dc5acd9a-675c-4f12-8c7e-67dd57d1e57b",
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Markdown for 'errors':\n",
      "[ sigstore](../sigstore.html)\n",
      "\n",
      "## API Documentation\n",
      "\n",
      "  * Error\n",
      "    * diagnostics\n",
      "    * print_and_exit\n",
      "  * NetworkError\n",
      "    * diagnostics\n",
      "  * TUFError\n",
      "    * TUFError\n",
      "    * message\n",
      "    * diagnostics\n",
      "  * MetadataError\n",
      "    * diagnostics\n",
      "  * RootError\n",
      "    * diagnostics\n",
      "\n",
      "[ built with pdoc ](https://pdoc.dev \"pdoc: Python API documentation\n",
      "generator\")\n",
      "\n",
      "#  [sigstore](./../sigstore.html).errors\n",
      "\n",
      "Exceptions.\n",
      "\n",
      "View Source\n",
      "\n",
      "    \n",
      "    \n",
      "      1# Copyright 2023 The Sigstore Authors\n",
      "      2#\n",
      "      3# Licensed under the Apache License, Version 2.0 (the \"License\");\n",
      "      4# you may not use this file except in compliance with the License.\n",
      "      5# You may obtain a copy of the License at\n",
      "      6#\n",
      "      7#      http://www.apache.org/licenses/LICENSE-2.0\n",
      "      8#\n",
      "      9# Unless required by applicable law or agreed to in writing, software\n",
      "     10# distributed under the License is distributed on an \"AS IS\" BASIS,\n",
      "     11# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n",
      "     12# See the License for the specific language governing permissions and\n",
      "     13# limitations under the License.\n",
      "     14\n",
      "     15\"\"\"\n",
      "     16Exceptions.\n",
      "     17\"\"\"\n",
      "     18\n",
      "     19import sys\n",
      "     20from typing import Any, Mapping\n",
      "     21\n",
      "     22\n",
      "     23class Error(Exception):\n",
      "     24    \"\"\"Base sigstore exception type. Defines helpers for diagnostics.\"\"\"\n",
      "     25\n",
      "     26    def diagnostics(self) -> str:\n",
      "     27        \"\"\"Returns human-friendly error information.\"\"\"\n",
      "     28\n",
      "     29        return \"\"\"An issue occurred.\"\"\"\n",
      "     30\n",
      "     31    def print_and_exit(self, raise_error: bool = False) -> None:\n",
      "     32        \"\"\"Prints all relevant error information to stderr and exits.\"\"\"\n",
      "     33\n",
      "     34        remind_verbose = (\n",
      "     35            \"Raising original exception:\"\n",
      "     36            if raise_error\n",
      "     37            else \"For detailed error information, run sigstore with the `--verbose` flag.\"\n",
      "     38        )\n",
      "     39\n",
      "     40        print(f\"{self.diagnostics()}\\n{remind_verbose}\", file=sys.stderr)\n",
      "     41\n",
      "     42        if raise_error:\n",
      "     43            # don't want \"during handling another exception\"\n",
      "     44            self.__suppress_context__ = True\n",
      "     45            raise self\n",
      "     46\n",
      "     47        sys.exit(1)\n",
      "     48\n",
      "     49\n",
      "     50class NetworkError(Error):\n",
      "     51    \"\"\"Raised when a connectivity-related issue occurs.\"\"\"\n",
      "     52\n",
      "     53    def diagnostics(self) -> str:\n",
      "     54        \"\"\"Returns diagnostics for the error.\"\"\"\n",
      "     55\n",
      "     56        cause_ctx = (\n",
      "     57            f\"\"\"\n",
      "     58        Additional context:\n",
      "     59\n",
      "     60        {self.__cause__}\n",
      "     61        \"\"\"\n",
      "     62            if self.__cause__\n",
      "     63            else \"\"\n",
      "     64        )\n",
      "     65\n",
      "     66        return (\n",
      "     67            \"\"\"\\\n",
      "     68        A network issue occurred.\n",
      "     69\n",
      "     70        Check your internet connection and try again.\n",
      "     71        \"\"\"\n",
      "     72            + cause_ctx\n",
      "     73        )\n",
      "     74\n",
      "     75\n",
      "     76class TUFError(Error):\n",
      "     77    \"\"\"Raised when a TUF error occurs.\"\"\"\n",
      "     78\n",
      "     79    def __init__(self, message: str):\n",
      "     80        \"\"\"Constructs a `TUFError`.\"\"\"\n",
      "     81        self.message = message\n",
      "     82\n",
      "     83    from tuf.api import exceptions\n",
      "     84\n",
      "     85    _details: Mapping[Any, str] = {\n",
      "     86        exceptions.DownloadError: NetworkError().diagnostics()\n",
      "     87    }\n",
      "     88\n",
      "     89    def diagnostics(self) -> str:\n",
      "     90        \"\"\"Returns diagnostics specialized to the wrapped TUF error.\"\"\"\n",
      "     91        details = TUFError._details.get(\n",
      "     92            type(self.__context__),\n",
      "     93            \"Please report this issue at <https://github.com/sigstore/sigstore-python/issues/new>.\",\n",
      "     94        )\n",
      "     95\n",
      "     96        return f\"\"\"\\\n",
      "     97        {self.message}.\n",
      "     98\n",
      "     99        {details}\n",
      "    100        \"\"\"\n",
      "    101\n",
      "    102\n",
      "    103class MetadataError(Error):\n",
      "    104    \"\"\"Raised when TUF metadata does not conform to the expected structure.\"\"\"\n",
      "    105\n",
      "    106    def diagnostics(self) -> str:\n",
      "    107        \"\"\"Returns diagnostics for the error.\"\"\"\n",
      "    108        return f\"\"\"{str(self)}.\"\"\"\n",
      "    109\n",
      "    110\n",
      "    111class RootError(Error):\n",
      "    112    \"\"\"Raised when TUF cannot establish its root of trust.\"\"\"\n",
      "    113\n",
      "    114    def diagnostics(self) -> str:\n",
      "    115        \"\"\"Returns diagnostics for the error.\"\"\"\n",
      "    116        return \"\"\"\\\n",
      "    117        Unable to establish root of trust.\n",
      "    118\n",
      "    119        This error may occur when the resources embedded in this distribution of sigstore-python are out of date.\"\"\"\n",
      "    \n",
      "\n",
      "class Error(builtins.Exception): View Source\n",
      "\n",
      "    \n",
      "    \n",
      "    24class Error(Exception):\n",
      "    25    \"\"\"Base sigstore exception type. Defines helpers for diagnostics.\"\"\"\n",
      "    26\n",
      "    27    def diagnostics(self) -> str:\n",
      "    28        \"\"\"Returns human-friendly error information.\"\"\"\n",
      "    29\n",
      "    30        return \"\"\"An issue occurred.\"\"\"\n",
      "    31\n",
      "    32    def print_and_exit(self, raise_error: bool = False) -> None:\n",
      "    33        \"\"\"Prints all relevant error information to stderr and exits.\"\"\"\n",
      "    34\n",
      "    35        remind_verbose = (\n",
      "    36            \"Raising original exception:\"\n",
      "    37            if raise_error\n",
      "    38            else \"For detailed error information, run sigstore with the `--verbose` flag.\"\n",
      "    39        )\n",
      "    40\n",
      "    41        print(f\"{self.diagnostics()}\\n{remind_verbose}\", file=sys.stderr)\n",
      "    42\n",
      "    43        if raise_error:\n",
      "    44            # don't want \"during handling another exception\"\n",
      "    45            self.__suppress_context__ = True\n",
      "    46            raise self\n",
      "    47\n",
      "    48        sys.exit(1)\n",
      "    \n",
      "\n",
      "Base sigstore exception type. Defines helpers for diagnostics.\n",
      "\n",
      "def diagnostics(self) -> str: View Source\n",
      "\n",
      "    \n",
      "    \n",
      "    27    def diagnostics(self) -> str:\n",
      "    28        \"\"\"Returns human-friendly error information.\"\"\"\n",
      "    29\n",
      "    30        return \"\"\"An issue occurred.\"\"\"\n",
      "    \n",
      "\n",
      "Returns human-friendly error information.\n",
      "\n",
      "def print_and_exit(self, raise_error: bool = False) -> None: View Source\n",
      "\n",
      "    \n",
      "    \n",
      "    32    def print_and_exit(self, raise_error: bool = False) -> None:\n",
      "    33        \"\"\"Prints all relevant error information to stderr and exits.\"\"\"\n",
      "    34\n",
      "    35        remind_verbose = (\n",
      "    36            \"Raising original exception:\"\n",
      "    37            if raise_error\n",
      "    38            else \"For detailed error information, run sigstore with the `--verbose` flag.\"\n",
      "    39        )\n",
      "    40\n",
      "    41        print(f\"{self.diagnostics()}\\n{remind_verbose}\", file=sys.stderr)\n",
      "    42\n",
      "    43        if raise_error:\n",
      "    44            # don't want \"during handling another exception\"\n",
      "    45            self.__suppress_context__ = True\n",
      "    46            raise self\n",
      "    47\n",
      "    48        sys.exit(1)\n",
      "    \n",
      "\n",
      "Prints all relevant error information to stderr and exits.\n",
      "\n",
      "##### Inherited Members\n",
      "\n",
      "builtins.Exception\n",
      "\n",
      "    Exception\n",
      "\n",
      "builtins.BaseException\n",
      "\n",
      "    with_traceback\n",
      "    add_note\n",
      "    args\n",
      "\n",
      "class NetworkError(Error): View Source\n",
      "\n",
      "    \n",
      "    \n",
      "    51class NetworkError(Error):\n",
      "    52    \"\"\"Raised when a connectivity-related issue occurs.\"\"\"\n",
      "    53\n",
      "    54    def diagnostics(self) -> str:\n",
      "    55        \"\"\"Returns diagnostics for the error.\"\"\"\n",
      "    56\n",
      "    57        cause_ctx = (\n",
      "    58            f\"\"\"\n",
      "    59        Additional context:\n",
      "    60\n",
      "    61        {self.__cause__}\n",
      "    62        \"\"\"\n",
      "    63            if self.__cause__\n",
      "    64            else \"\"\n",
      "    65        )\n",
      "    66\n",
      "    67        return (\n",
      "    68            \"\"\"\\\n",
      "    69        A network issue occurred.\n",
      "    70\n",
      "    71        Check your internet connection and try again.\n",
      "    72        \"\"\"\n",
      "    73            + cause_ctx\n",
      "    74        )\n",
      "    \n",
      "\n",
      "Raised when a connectivity-related issue occurs.\n",
      "\n",
      "def diagnostics(self) -> str: View Source\n",
      "\n",
      "    \n",
      "    \n",
      "    54    def diagnostics(self) -> str:\n",
      "    55        \"\"\"Returns diagnostics for the error.\"\"\"\n",
      "    56\n",
      "    57        cause_ctx = (\n",
      "    58            f\"\"\"\n",
      "    59        Additional context:\n",
      "    60\n",
      "    61        {self.__cause__}\n",
      "    62        \"\"\"\n",
      "    63            if self.__cause__\n",
      "    64            else \"\"\n",
      "    65        )\n",
      "    66\n",
      "    67        return (\n",
      "    68            \"\"\"\\\n",
      "    69        A network issue occurred.\n",
      "    70\n",
      "    71        Check your internet connection and try again.\n",
      "    72        \"\"\"\n",
      "    73            + cause_ctx\n",
      "    74        )\n",
      "    \n",
      "\n",
      "Returns diagnostics for the error.\n",
      "\n",
      "##### Inherited Members\n",
      "\n",
      "builtins.Exception\n",
      "\n",
      "    Exception\n",
      "\n",
      "Error\n",
      "\n",
      "    print_and_exit\n",
      "\n",
      "builtins.BaseException\n",
      "\n",
      "    with_traceback\n",
      "    add_note\n",
      "    args\n",
      "\n",
      "class TUFError(Error): View Source\n",
      "\n",
      "    \n",
      "    \n",
      "     77class TUFError(Error):\n",
      "     78    \"\"\"Raised when a TUF error occurs.\"\"\"\n",
      "     79\n",
      "     80    def __init__(self, message: str):\n",
      "     81        \"\"\"Constructs a `TUFError`.\"\"\"\n",
      "     82        self.message = message\n",
      "     83\n",
      "     84    from tuf.api import exceptions\n",
      "     85\n",
      "     86    _details: Mapping[Any, str] = {\n",
      "     87        exceptions.DownloadError: NetworkError().diagnostics()\n",
      "     88    }\n",
      "     89\n",
      "     90    def diagnostics(self) -> str:\n",
      "     91        \"\"\"Returns diagnostics specialized to the wrapped TUF error.\"\"\"\n",
      "     92        details = TUFError._details.get(\n",
      "     93            type(self.__context__),\n",
      "     94            \"Please report this issue at <https://github.com/sigstore/sigstore-python/issues/new>.\",\n",
      "     95        )\n",
      "     96\n",
      "     97        return f\"\"\"\\\n",
      "     98        {self.message}.\n",
      "     99\n",
      "    100        {details}\n",
      "    101        \"\"\"\n",
      "    \n",
      "\n",
      "Raised when a TUF error occurs.\n",
      "\n",
      "TUFError(message: str) View Source\n",
      "\n",
      "    \n",
      "    \n",
      "    80    def __init__(self, message: str):\n",
      "    81        \"\"\"Constructs a `TUFError`.\"\"\"\n",
      "    82        self.message = message\n",
      "    \n",
      "\n",
      "Constructs a `TUFError`.\n",
      "\n",
      "message\n",
      "\n",
      "def diagnostics(self) -> str: View Source\n",
      "\n",
      "    \n",
      "    \n",
      "     90    def diagnostics(self) -> str:\n",
      "     91        \"\"\"Returns diagnostics specialized to the wrapped TUF error.\"\"\"\n",
      "     92        details = TUFError._details.get(\n",
      "     93            type(self.__context__),\n",
      "     94            \"Please report this issue at <https://github.com/sigstore/sigstore-python/issues/new>.\",\n",
      "     95        )\n",
      "     96\n",
      "     97        return f\"\"\"\\\n",
      "     98        {self.message}.\n",
      "     99\n",
      "    100        {details}\n",
      "    101        \"\"\"\n",
      "    \n",
      "\n",
      "Returns diagnostics specialized to the wrapped TUF error.\n",
      "\n",
      "##### Inherited Members\n",
      "\n",
      "Error\n",
      "\n",
      "    print_and_exit\n",
      "\n",
      "builtins.BaseException\n",
      "\n",
      "    with_traceback\n",
      "    add_note\n",
      "    args\n",
      "\n",
      "class MetadataError(Error): View Source\n",
      "\n",
      "    \n",
      "    \n",
      "    104class MetadataError(Error):\n",
      "    105    \"\"\"Raised when TUF metadata does not conform to the expected structure.\"\"\"\n",
      "    106\n",
      "    107    def diagnostics(self) -> str:\n",
      "    108        \"\"\"Returns diagnostics for the error.\"\"\"\n",
      "    109        return f\"\"\"{str(self)}.\"\"\"\n",
      "    \n",
      "\n",
      "Raised when TUF metadata does not conform to the expected structure.\n",
      "\n",
      "def diagnostics(self) -> str: View Source\n",
      "\n",
      "    \n",
      "    \n",
      "    107    def diagnostics(self) -> str:\n",
      "    108        \"\"\"Returns diagnostics for the error.\"\"\"\n",
      "    109        return f\"\"\"{str(self)}.\"\"\"\n",
      "    \n",
      "\n",
      "Returns diagnostics for the error.\n",
      "\n",
      "##### Inherited Members\n",
      "\n",
      "builtins.Exception\n",
      "\n",
      "    Exception\n",
      "\n",
      "Error\n",
      "\n",
      "    print_and_exit\n",
      "\n",
      "builtins.BaseException\n",
      "\n",
      "    with_traceback\n",
      "    add_note\n",
      "    args\n",
      "\n",
      "class RootError(Error): View Source\n",
      "\n",
      "    \n",
      "    \n",
      "    112class RootError(Error):\n",
      "    113    \"\"\"Raised when TUF cannot establish its root of trust.\"\"\"\n",
      "    114\n",
      "    115    def diagnostics(self) -> str:\n",
      "    116        \"\"\"Returns diagnostics for the error.\"\"\"\n",
      "    117        return \"\"\"\\\n",
      "    118        Unable to establish root of trust.\n",
      "    119\n",
      "    120        This error may occur when the resources embedded in this distribution of sigstore-python are out of date.\"\"\"\n",
      "    \n",
      "\n",
      "Raised when TUF cannot establish its root of trust.\n",
      "\n",
      "def diagnostics(self) -> str: View Source\n",
      "\n",
      "    \n",
      "    \n",
      "    115    def diagnostics(self) -> str:\n",
      "    116        \"\"\"Returns diagnostics for the error.\"\"\"\n",
      "    117        return \"\"\"\\\n",
      "    118        Unable to establish root of trust.\n",
      "    119\n",
      "    120        This error may occur when the resources embedded in this distribution of sigstore-python are out of date.\"\"\"\n",
      "    \n",
      "\n",
      "Returns diagnostics for the error.\n",
      "\n",
      "##### Inherited Members\n",
      "\n",
      "builtins.Exception\n",
      "\n",
      "    Exception\n",
      "\n",
      "Error\n",
      "\n",
      "    print_and_exit\n",
      "\n",
      "builtins.BaseException\n",
      "\n",
      "    with_traceback\n",
      "    add_note\n",
      "    args\n",
      "\n",
      "\n",
      "Markdown for 'oidc':\n",
      "[ sigstore](../sigstore.html)\n",
      "\n",
      "## API Documentation\n",
      "\n",
      "  * DEFAULT_OAUTH_ISSUER_URL\n",
      "  * STAGING_OAUTH_ISSUER_URL\n",
      "  * DEFAULT_AUDIENCE\n",
      "  * ExpiredIdentity\n",
      "  * IdentityToken\n",
      "    * IdentityToken\n",
      "    * in_validity_period\n",
      "    * identity\n",
      "    * issuer\n",
      "    * expected_certificate_subject\n",
      "  * IssuerError\n",
      "  * Issuer\n",
      "    * Issuer\n",
      "    * production\n",
      "    * staging\n",
      "    * identity_token\n",
      "  * IdentityError\n",
      "    * raise_from_id\n",
      "    * diagnostics\n",
      "  * detect_credential\n",
      "\n",
      "[ built with pdoc ](https://pdoc.dev \"pdoc: Python API documentation\n",
      "generator\")\n",
      "\n",
      "#  [sigstore](./../sigstore.html).oidc\n",
      "\n",
      "API for retrieving OIDC tokens.\n",
      "\n",
      "View Source\n",
      "\n",
      "    \n",
      "    \n",
      "      1# Copyright 2022 The Sigstore Authors\n",
      "      2#\n",
      "      3# Licensed under the Apache License, Version 2.0 (the \"License\");\n",
      "      4# you may not use this file except in compliance with the License.\n",
      "      5# You may obtain a copy of the License at\n",
      "      6#\n",
      "      7#      http://www.apache.org/licenses/LICENSE-2.0\n",
      "      8#\n",
      "      9# Unless required by applicable law or agreed to in writing, software\n",
      "     10# distributed under the License is distributed on an \"AS IS\" BASIS,\n",
      "     11# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n",
      "     12# See the License for the specific language governing permissions and\n",
      "     13# limitations under the License.\n",
      "     14\n",
      "     15\"\"\"\n",
      "     16API for retrieving OIDC tokens.\n",
      "     17\"\"\"\n",
      "     18\n",
      "     19from __future__ import annotations\n",
      "     20\n",
      "     21import logging\n",
      "     22import sys\n",
      "     23import time\n",
      "     24import urllib.parse\n",
      "     25import webbrowser\n",
      "     26from datetime import datetime, timezone\n",
      "     27from typing import NoReturn, Optional, cast\n",
      "     28\n",
      "     29import id\n",
      "     30import jwt\n",
      "     31import requests\n",
      "     32from pydantic import BaseModel, StrictStr\n",
      "     33\n",
      "     34from sigstore.errors import Error, NetworkError\n",
      "     35\n",
      "     36DEFAULT_OAUTH_ISSUER_URL = \"https://oauth2.sigstore.dev/auth\"\n",
      "     37STAGING_OAUTH_ISSUER_URL = \"https://oauth2.sigstage.dev/auth\"\n",
      "     38\n",
      "     39# See: https://github.com/sigstore/fulcio/blob/b2186c0/pkg/config/config.go#L182-L201\n",
      "     40_KNOWN_OIDC_ISSUERS = {\n",
      "     41    \"https://accounts.google.com\": \"email\",\n",
      "     42    \"https://oauth2.sigstore.dev/auth\": \"email\",\n",
      "     43    \"https://oauth2.sigstage.dev/auth\": \"email\",\n",
      "     44    \"https://token.actions.githubusercontent.com\": \"sub\",\n",
      "     45}\n",
      "     46_DEFAULT_AUDIENCE = \"sigstore\"\n",
      "     47\n",
      "     48\n",
      "     49class _OpenIDConfiguration(BaseModel):\n",
      "     50    \"\"\"\n",
      "     51    Represents a (subset) of the fields provided by an OpenID Connect provider's\n",
      "     52    `.well-known/openid-configuration` response, as defined by OpenID Connect Discovery.\n",
      "     53\n",
      "     54    See: <https://openid.net/specs/openid-connect-discovery-1_0.html>\n",
      "     55    \"\"\"\n",
      "     56\n",
      "     57    authorization_endpoint: StrictStr\n",
      "     58    token_endpoint: StrictStr\n",
      "     59\n",
      "     60\n",
      "     61# See: https://github.com/sigstore/fulcio/blob/b2186c0/pkg/config/config.go#L182-L201\n",
      "     62_KNOWN_OIDC_ISSUERS = {\n",
      "     63    \"https://accounts.google.com\": \"email\",\n",
      "     64    \"https://oauth2.sigstore.dev/auth\": \"email\",\n",
      "     65    \"https://oauth2.sigstage.dev/auth\": \"email\",\n",
      "     66    \"https://token.actions.githubusercontent.com\": \"sub\",\n",
      "     67}\n",
      "     68DEFAULT_AUDIENCE = \"sigstore\"\n",
      "     69\n",
      "     70\n",
      "     71class ExpiredIdentity(Exception):\n",
      "     72    \"\"\"An error raised when an identity token is expired.\"\"\"\n",
      "     73\n",
      "     74\n",
      "     75class IdentityToken:\n",
      "     76    \"\"\"\n",
      "     77    An OIDC \"identity\", corresponding to an underlying OIDC token with\n",
      "     78    a sensible subject, issuer, and audience for Sigstore purposes.\n",
      "     79    \"\"\"\n",
      "     80\n",
      "     81    def __init__(self, raw_token: str) -> None:\n",
      "     82        \"\"\"\n",
      "     83        Create a new `IdentityToken` from the given OIDC token.\n",
      "     84        \"\"\"\n",
      "     85\n",
      "     86        self._raw_token = raw_token\n",
      "     87\n",
      "     88        # NOTE: The lack of verification here is intentional, and is part of\n",
      "     89        # Sigstore's verification model: clients like sigstore-python are\n",
      "     90        # responsible only for forwarding the OIDC identity to Fulcio for\n",
      "     91        # certificate binding and issuance.\n",
      "     92        try:\n",
      "     93            self._unverified_claims = jwt.decode(\n",
      "     94                raw_token,\n",
      "     95                options={\n",
      "     96                    \"verify_signature\": False,\n",
      "     97                    \"verify_aud\": True,\n",
      "     98                    \"verify_iat\": True,\n",
      "     99                    \"verify_exp\": True,\n",
      "    100                    # These claims are required by OpenID Connect, so\n",
      "    101                    # we can strongly enforce their presence.\n",
      "    102                    # See: https://openid.net/specs/openid-connect-basic-1_0.html#IDToken\n",
      "    103                    \"require\": [\"aud\", \"sub\", \"iat\", \"exp\", \"iss\"],\n",
      "    104                },\n",
      "    105                audience=DEFAULT_AUDIENCE,\n",
      "    106                # NOTE: This leeway shouldn't be strictly necessary, but is\n",
      "    107                # included to preempt any (small) skew between the host\n",
      "    108                # and the originating IdP.\n",
      "    109                leeway=5,\n",
      "    110            )\n",
      "    111        except Exception as exc:\n",
      "    112            raise IdentityError(\n",
      "    113                \"Identity token is malformed or missing claims\"\n",
      "    114            ) from exc\n",
      "    115\n",
      "    116        self._iss: str = self._unverified_claims[\"iss\"]\n",
      "    117        self._nbf: int | None = self._unverified_claims.get(\"nbf\")\n",
      "    118        self._exp: int = self._unverified_claims[\"exp\"]\n",
      "    119\n",
      "    120        # Fail early if this token isn't within its validity period.\n",
      "    121        if not self.in_validity_period():\n",
      "    122            raise IdentityError(\"Identity token is not within its validity period\")\n",
      "    123\n",
      "    124        # When verifying the private key possession proof, Fulcio uses\n",
      "    125        # different claims depending on the token's issuer.\n",
      "    126        # We currently special-case a handful of these, and fall back\n",
      "    127        # on signing the \"sub\" claim otherwise.\n",
      "    128        identity_claim = _KNOWN_OIDC_ISSUERS.get(self.issuer)\n",
      "    129        if identity_claim is not None:\n",
      "    130            if identity_claim not in self._unverified_claims:\n",
      "    131                raise IdentityError(\n",
      "    132                    f\"Identity token is missing the required {identity_claim!r} claim\"\n",
      "    133                )\n",
      "    134\n",
      "    135            self._identity = str(self._unverified_claims.get(identity_claim))\n",
      "    136        else:\n",
      "    137            try:\n",
      "    138                self._identity = str(self._unverified_claims[\"sub\"])\n",
      "    139            except KeyError:\n",
      "    140                raise IdentityError(\n",
      "    141                    \"Identity token is missing the required 'sub' claim\"\n",
      "    142                )\n",
      "    143\n",
      "    144        # This identity token might have been retrieved directly from\n",
      "    145        # an identity provider, or it might be a \"federated\" identity token\n",
      "    146        # retrieved from a federated IdP (e.g., Sigstore's own Dex instance).\n",
      "    147        # In the latter case, the claims will also include a `federated_claims`\n",
      "    148        # set, which in turn should include a `connector_id` that reflects\n",
      "    149        # the \"real\" token issuer. We retrieve this, despite technically\n",
      "    150        # being an implementation detail, because it has value to client\n",
      "    151        # users: a client might want to make sure that its user is identifying\n",
      "    152        # with a *particular* IdP, which means that they need to pierce the\n",
      "    153        # federation layer to check which IdP is actually being used.\n",
      "    154        self._federated_issuer: str | None = None\n",
      "    155        federated_claims = self._unverified_claims.get(\"federated_claims\")\n",
      "    156        if federated_claims is not None:\n",
      "    157            if not isinstance(federated_claims, dict):\n",
      "    158                raise IdentityError(\n",
      "    159                    \"unexpected claim type: federated_claims is not a dict\"\n",
      "    160                )\n",
      "    161\n",
      "    162            federated_issuer = federated_claims.get(\"connector_id\")\n",
      "    163            if federated_issuer is not None:\n",
      "    164                if not isinstance(federated_issuer, str):\n",
      "    165                    raise IdentityError(\n",
      "    166                        \"unexpected claim type: federated_claims.connector_id is not a string\"\n",
      "    167                    )\n",
      "    168\n",
      "    169                self._federated_issuer = federated_issuer\n",
      "    170\n",
      "    171    def in_validity_period(self) -> bool:\n",
      "    172        \"\"\"\n",
      "    173        Returns whether or not this `Identity` is currently within its self-stated validity period.\n",
      "    174\n",
      "    175        NOTE: As noted in `Identity.__init__`, this is not a verifying wrapper;\n",
      "    176        the check here only asserts whether the *unverified* identity's claims\n",
      "    177        are within their validity period.\n",
      "    178        \"\"\"\n",
      "    179\n",
      "    180        now = datetime.now(timezone.utc).timestamp()\n",
      "    181\n",
      "    182        if self._nbf is not None:\n",
      "    183            return self._nbf <= now < self._exp\n",
      "    184        else:\n",
      "    185            return now < self._exp\n",
      "    186\n",
      "    187    @property\n",
      "    188    def identity(self) -> str:\n",
      "    189        \"\"\"\n",
      "    190        Returns this `IdentityToken`'s underlying \"subject\".\n",
      "    191\n",
      "    192        Note that this is **not** always the `sub` claim in the corresponding\n",
      "    193        identity token: depending onm the token's issuer, it may be a *different*\n",
      "    194        claim, such as `email`. This corresponds to the Sigstore ecosystem's\n",
      "    195        behavior, e.g. in each issued certificate's SAN.\n",
      "    196        \"\"\"\n",
      "    197        return self._identity\n",
      "    198\n",
      "    199    @property\n",
      "    200    def issuer(self) -> str:\n",
      "    201        \"\"\"\n",
      "    202        Returns a URL identifying this `IdentityToken`'s issuer.\n",
      "    203        \"\"\"\n",
      "    204        return self._iss\n",
      "    205\n",
      "    206    @property\n",
      "    207    def expected_certificate_subject(self) -> str:\n",
      "    208        \"\"\"\n",
      "    209        Returns a URL identifying the **expected** subject for any Sigstore\n",
      "    210        certificate issued against this identity token.\n",
      "    211\n",
      "    212        The behavior of this field is slightly subtle: for non-federated\n",
      "    213        identity providers (like a token issued directly by Google's IdP) it\n",
      "    214        should be exactly equivalent to `IdentityToken.issuer`. For federated\n",
      "    215        issuers (like Sigstore's own federated IdP) it should be equivalent to\n",
      "    216        the underlying federated issuer's URL, which is kept in an\n",
      "    217        implementation-defined claim.\n",
      "    218\n",
      "    219        This attribute exists so that clients who wish to inspect the expected\n",
      "    220        subject of their certificates can do so without relying on\n",
      "    221        implementation-specific behavior.\n",
      "    222        \"\"\"\n",
      "    223        if self._federated_issuer is not None:\n",
      "    224            return self._federated_issuer\n",
      "    225\n",
      "    226        return self.issuer\n",
      "    227\n",
      "    228    def __str__(self) -> str:\n",
      "    229        \"\"\"\n",
      "    230        Returns the underlying OIDC token for this identity.\n",
      "    231\n",
      "    232        That this token is secret in nature and **MUST NOT** be disclosed.\n",
      "    233        \"\"\"\n",
      "    234        return self._raw_token\n",
      "    235\n",
      "    236\n",
      "    237class IssuerError(Exception):\n",
      "    238    \"\"\"\n",
      "    239    Raised on any communication or format error with an OIDC issuer.\n",
      "    240    \"\"\"\n",
      "    241\n",
      "    242    pass\n",
      "    243\n",
      "    244\n",
      "    245class Issuer:\n",
      "    246    \"\"\"\n",
      "    247    Represents an OIDC issuer (IdP).\n",
      "    248    \"\"\"\n",
      "    249\n",
      "    250    def __init__(self, base_url: str) -> None:\n",
      "    251        \"\"\"\n",
      "    252        Create a new `Issuer` from the given base URL.\n",
      "    253\n",
      "    254        This URL is used to locate an OpenID Connect configuration file,\n",
      "    255        which is then used to bootstrap the issuer's state (such\n",
      "    256        as authorization and token endpoints).\n",
      "    257        \"\"\"\n",
      "    258        oidc_config_url = urllib.parse.urljoin(\n",
      "    259            f\"{base_url}/\", \".well-known/openid-configuration\"\n",
      "    260        )\n",
      "    261\n",
      "    262        try:\n",
      "    263            resp: requests.Response = requests.get(oidc_config_url, timeout=30)\n",
      "    264        except (requests.ConnectionError, requests.Timeout) as exc:\n",
      "    265            raise NetworkError from exc\n",
      "    266\n",
      "    267        try:\n",
      "    268            resp.raise_for_status()\n",
      "    269        except requests.HTTPError as http_error:\n",
      "    270            raise IssuerError from http_error\n",
      "    271\n",
      "    272        try:\n",
      "    273            # We don't generally expect this to fail (since the provider should\n",
      "    274            # return a non-success HTTP code which we catch above), but we\n",
      "    275            # check just in case we have a misbehaving OIDC issuer.\n",
      "    276            self.oidc_config = _OpenIDConfiguration.model_validate(resp.json())\n",
      "    277        except ValueError as exc:\n",
      "    278            raise IssuerError(f\"OIDC issuer returned invalid configuration: {exc}\")\n",
      "    279\n",
      "    280    @classmethod\n",
      "    281    def production(cls) -> Issuer:\n",
      "    282        \"\"\"\n",
      "    283        Returns an `Issuer` configured against Sigstore's production-level services.\n",
      "    284        \"\"\"\n",
      "    285        return cls(DEFAULT_OAUTH_ISSUER_URL)\n",
      "    286\n",
      "    287    @classmethod\n",
      "    288    def staging(cls) -> Issuer:\n",
      "    289        \"\"\"\n",
      "    290        Returns an `Issuer` configured against Sigstore's staging-level services.\n",
      "    291        \"\"\"\n",
      "    292        return cls(STAGING_OAUTH_ISSUER_URL)\n",
      "    293\n",
      "    294    def identity_token(  # nosec: B107\n",
      "    295        self,\n",
      "    296        client_id: str = \"sigstore\",\n",
      "    297        client_secret: str = \"\",\n",
      "    298        force_oob: bool = False,\n",
      "    299    ) -> IdentityToken:\n",
      "    300        \"\"\"\n",
      "    301        Retrieves and returns an `IdentityToken` from the current `Issuer`, via OAuth.\n",
      "    302\n",
      "    303        This function blocks on user interaction.\n",
      "    304\n",
      "    305        The `force_oob` flag controls the kind of flow performed. When `False` (the default),\n",
      "    306        this function attempts to open the user's web browser before falling back to\n",
      "    307        an out-of-band flow. When `True`, the out-of-band flow is always used.\n",
      "    308        \"\"\"\n",
      "    309\n",
      "    310        # This function and the components that it relies on are based off of:\n",
      "    311        # https://github.com/psteniusubi/python-sample\n",
      "    312\n",
      "    313        from sigstore._internal.oidc.oauth import _OAuthFlow\n",
      "    314\n",
      "    315        code: str\n",
      "    316        with _OAuthFlow(client_id, client_secret, self) as server:\n",
      "    317            # Launch web browser\n",
      "    318            if not force_oob and webbrowser.open(server.base_uri):\n",
      "    319                print(\"Waiting for browser interaction...\", file=sys.stderr)\n",
      "    320            else:\n",
      "    321                server.enable_oob()\n",
      "    322                print(\n",
      "    323                    f\"Go to the following link in a browser:\\n\\n\\t{server.auth_endpoint}\",\n",
      "    324                    file=sys.stderr,\n",
      "    325                )\n",
      "    326\n",
      "    327            if not server.is_oob():\n",
      "    328                # Wait until the redirect server populates the response\n",
      "    329                while server.auth_response is None:\n",
      "    330                    time.sleep(0.1)\n",
      "    331\n",
      "    332                auth_error = server.auth_response.get(\"error\")\n",
      "    333                if auth_error is not None:\n",
      "    334                    raise IdentityError(\n",
      "    335                        f\"Error response from auth endpoint: {auth_error[0]}\"\n",
      "    336                    )\n",
      "    337                code = server.auth_response[\"code\"][0]\n",
      "    338            else:\n",
      "    339                # In the out-of-band case, we wait until the user provides the code\n",
      "    340                code = input(\"Enter verification code: \")\n",
      "    341\n",
      "    342        # Provide code to token endpoint\n",
      "    343        data = {\n",
      "    344            \"grant_type\": \"authorization_code\",\n",
      "    345            \"redirect_uri\": server.redirect_uri,\n",
      "    346            \"code\": code,\n",
      "    347            \"code_verifier\": server.oauth_session.code_verifier,\n",
      "    348        }\n",
      "    349        auth = (\n",
      "    350            client_id,\n",
      "    351            client_secret,\n",
      "    352        )\n",
      "    353        logging.debug(f\"PAYLOAD: data={data}\")\n",
      "    354        try:\n",
      "    355            resp: requests.Response = requests.post(\n",
      "    356                self.oidc_config.token_endpoint,\n",
      "    357                data=data,\n",
      "    358                auth=auth,\n",
      "    359                timeout=30,\n",
      "    360            )\n",
      "    361        except (requests.ConnectionError, requests.Timeout) as exc:\n",
      "    362            raise NetworkError from exc\n",
      "    363\n",
      "    364        try:\n",
      "    365            resp.raise_for_status()\n",
      "    366        except requests.HTTPError as http_error:\n",
      "    367            raise IdentityError(\n",
      "    368                f\"Token request failed with {resp.status_code}\"\n",
      "    369            ) from http_error\n",
      "    370\n",
      "    371        token_json = resp.json()\n",
      "    372        token_error = token_json.get(\"error\")\n",
      "    373        if token_error is not None:\n",
      "    374            raise IdentityError(f\"Error response from token endpoint: {token_error}\")\n",
      "    375\n",
      "    376        return IdentityToken(token_json[\"access_token\"])\n",
      "    377\n",
      "    378\n",
      "    379class IdentityError(Error):\n",
      "    380    \"\"\"\n",
      "    381    Wraps `id`'s IdentityError.\n",
      "    382    \"\"\"\n",
      "    383\n",
      "    384    @classmethod\n",
      "    385    def raise_from_id(cls, exc: id.IdentityError) -> NoReturn:\n",
      "    386        \"\"\"Raises a wrapped IdentityError from the provided `id.IdentityError`.\"\"\"\n",
      "    387        raise cls(str(exc)) from exc\n",
      "    388\n",
      "    389    def diagnostics(self) -> str:\n",
      "    390        \"\"\"Returns diagnostics for the error.\"\"\"\n",
      "    391        if isinstance(self.__cause__, id.GitHubOidcPermissionCredentialError):\n",
      "    392            return f\"\"\"\n",
      "    393                Insufficient permissions for GitHub Actions workflow.\n",
      "    394\n",
      "    395                The most common reason for this is incorrect\n",
      "    396                configuration of the top-level `permissions` setting of the\n",
      "    397                workflow YAML file. It should be configured like so:\n",
      "    398\n",
      "    399                    permissions:\n",
      "    400                      id-token: write\n",
      "    401\n",
      "    402                Relevant documentation here:\n",
      "    403\n",
      "    404                    https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect#adding-permissions-settings\n",
      "    405\n",
      "    406                Another possible reason is that the workflow run has been\n",
      "    407                triggered by a PR from a forked repository. PRs from forked\n",
      "    408                repositories typically cannot be granted write access.\n",
      "    409\n",
      "    410                Relevant documentation here:\n",
      "    411\n",
      "    412                    https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token\n",
      "    413\n",
      "    414                Additional context:\n",
      "    415\n",
      "    416                {self.__cause__}\n",
      "    417                \"\"\"\n",
      "    418        else:\n",
      "    419            return f\"\"\"\n",
      "    420                An issue occurred with ambient credential detection.\n",
      "    421\n",
      "    422                Additional context:\n",
      "    423\n",
      "    424                {self}\n",
      "    425            \"\"\"\n",
      "    426\n",
      "    427\n",
      "    428def detect_credential() -> Optional[str]:\n",
      "    429    \"\"\"Calls `id.detect_credential`, but wraps exceptions with our own exception type.\"\"\"\n",
      "    430    try:\n",
      "    431        return cast(Optional[str], id.detect_credential(_DEFAULT_AUDIENCE))\n",
      "    432    except id.IdentityError as exc:\n",
      "    433        IdentityError.raise_from_id(exc)\n",
      "    \n",
      "\n",
      "DEFAULT_OAUTH_ISSUER_URL = 'https://oauth2.sigstore.dev/auth'\n",
      "\n",
      "STAGING_OAUTH_ISSUER_URL = 'https://oauth2.sigstage.dev/auth'\n",
      "\n",
      "DEFAULT_AUDIENCE = 'sigstore'\n",
      "\n",
      "class ExpiredIdentity(builtins.Exception): View Source\n",
      "\n",
      "    \n",
      "    \n",
      "    72class ExpiredIdentity(Exception):\n",
      "    73    \"\"\"An error raised when an identity token is expired.\"\"\"\n",
      "    \n",
      "\n",
      "An error raised when an identity token is expired.\n",
      "\n",
      "##### Inherited Members\n",
      "\n",
      "builtins.Exception\n",
      "\n",
      "    Exception\n",
      "\n",
      "builtins.BaseException\n",
      "\n",
      "    with_traceback\n",
      "    add_note\n",
      "    args\n",
      "\n",
      "class IdentityToken: View Source\n",
      "\n",
      "    \n",
      "    \n",
      "     76class IdentityToken:\n",
      "     77    \"\"\"\n",
      "     78    An OIDC \"identity\", corresponding to an underlying OIDC token with\n",
      "     79    a sensible subject, issuer, and audience for Sigstore purposes.\n",
      "     80    \"\"\"\n",
      "     81\n",
      "     82    def __init__(self, raw_token: str) -> None:\n",
      "     83        \"\"\"\n",
      "     84        Create a new `IdentityToken` from the given OIDC token.\n",
      "     85        \"\"\"\n",
      "     86\n",
      "     87        self._raw_token = raw_token\n",
      "     88\n",
      "     89        # NOTE: The lack of verification here is intentional, and is part of\n",
      "     90        # Sigstore's verification model: clients like sigstore-python are\n",
      "     91        # responsible only for forwarding the OIDC identity to Fulcio for\n",
      "     92        # certificate binding and issuance.\n",
      "     93        try:\n",
      "     94            self._unverified_claims = jwt.decode(\n",
      "     95                raw_token,\n",
      "     96                options={\n",
      "     97                    \"verify_signature\": False,\n",
      "     98                    \"verify_aud\": True,\n",
      "     99                    \"verify_iat\": True,\n",
      "    100                    \"verify_exp\": True,\n",
      "    101                    # These claims are required by OpenID Connect, so\n",
      "    102                    # we can strongly enforce their presence.\n",
      "    103                    # See: https://openid.net/specs/openid-connect-basic-1_0.html#IDToken\n",
      "    104                    \"require\": [\"aud\", \"sub\", \"iat\", \"exp\", \"iss\"],\n",
      "    105                },\n",
      "    106                audience=DEFAULT_AUDIENCE,\n",
      "    107                # NOTE: This leeway shouldn't be strictly necessary, but is\n",
      "    108                # included to preempt any (small) skew between the host\n",
      "    109                # and the originating IdP.\n",
      "    110                leeway=5,\n",
      "    111            )\n",
      "    112        except Exception as exc:\n",
      "    113            raise IdentityError(\n",
      "    114                \"Identity token is malformed or missing claims\"\n",
      "    115            ) from exc\n",
      "    116\n",
      "    117        self._iss: str = self._unverified_claims[\"iss\"]\n",
      "    118        self._nbf: int | None = self._unverified_claims.get(\"nbf\")\n",
      "    119        self._exp: int = self._unverified_claims[\"exp\"]\n",
      "    120\n",
      "    121        # Fail early if this token isn't within its validity period.\n",
      "    122        if not self.in_validity_period():\n",
      "    123            raise IdentityError(\"Identity token is not within its validity period\")\n",
      "    124\n",
      "    125        # When verifying the private key possession proof, Fulcio uses\n",
      "    126        # different claims depending on the token's issuer.\n",
      "    127        # We currently special-case a handful of these, and fall back\n",
      "    128        # on signing the \"sub\" claim otherwise.\n",
      "    129        identity_claim = _KNOWN_OIDC_ISSUERS.get(self.issuer)\n",
      "    130        if identity_claim is not None:\n",
      "    131            if identity_claim not in self._unverified_claims:\n",
      "    132                raise IdentityError(\n",
      "    133                    f\"Identity token is missing the required {identity_claim!r} claim\"\n",
      "    134                )\n",
      "    135\n",
      "    136            self._identity = str(self._unverified_claims.get(identity_claim))\n",
      "    137        else:\n",
      "    138            try:\n",
      "    139                self._identity = str(self._unverified_claims[\"sub\"])\n",
      "    140            except KeyError:\n",
      "    141                raise IdentityError(\n",
      "    142                    \"Identity token is missing the required 'sub' claim\"\n",
      "    143                )\n",
      "    144\n",
      "    145        # This identity token might have been retrieved directly from\n",
      "    146        # an identity provider, or it might be a \"federated\" identity token\n",
      "    147        # retrieved from a federated IdP (e.g., Sigstore's own Dex instance).\n",
      "    148        # In the latter case, the claims will also include a `federated_claims`\n",
      "    149        # set, which in turn should include a `connector_id` that reflects\n",
      "    150        # the \"real\" token issuer. We retrieve this, despite technically\n",
      "    151        # being an implementation detail, because it has value to client\n",
      "    152        # users: a client might want to make sure that its user is identifying\n",
      "    153        # with a *particular* IdP, which means that they need to pierce the\n",
      "    154        # federation layer to check which IdP is actually being used.\n",
      "    155        self._federated_issuer: str | None = None\n",
      "    156        federated_claims = self._unverified_claims.get(\"federated_claims\")\n",
      "    157        if federated_claims is not None:\n",
      "    158            if not isinstance(federated_claims, dict):\n",
      "    159                raise IdentityError(\n",
      "    160                    \"unexpected claim type: federated_claims is not a dict\"\n",
      "    161                )\n",
      "    162\n",
      "    163            federated_issuer = federated_claims.get(\"connector_id\")\n",
      "    164            if federated_issuer is not None:\n",
      "    165                if not isinstance(federated_issuer, str):\n",
      "    166                    raise IdentityError(\n",
      "    167                        \"unexpected claim type: federated_claims.connector_id is not a string\"\n",
      "    168                    )\n",
      "    169\n",
      "    170                self._federated_issuer = federated_issuer\n",
      "    171\n",
      "    172    def in_validity_period(self) -> bool:\n",
      "    173        \"\"\"\n",
      "    174        Returns whether or not this `Identity` is currently within its self-stated validity period.\n",
      "    175\n",
      "    176        NOTE: As noted in `Identity.__init__`, this is not a verifying wrapper;\n",
      "    177        the check here only asserts whether the *unverified* identity's claims\n",
      "    178        are within their validity period.\n",
      "    179        \"\"\"\n",
      "    180\n",
      "    181        now = datetime.now(timezone.utc).timestamp()\n",
      "    182\n",
      "    183        if self._nbf is not None:\n",
      "    184            return self._nbf <= now < self._exp\n",
      "    185        else:\n",
      "    186            return now < self._exp\n",
      "    187\n",
      "    188    @property\n",
      "    189    def identity(self) -> str:\n",
      "    190        \"\"\"\n",
      "    191        Returns this `IdentityToken`'s underlying \"subject\".\n",
      "    192\n",
      "    193        Note that this is **not** always the `sub` claim in the corresponding\n",
      "    194        identity token: depending onm the token's issuer, it may be a *different*\n",
      "    195        claim, such as `email`. This corresponds to the Sigstore ecosystem's\n",
      "    196        behavior, e.g. in each issued certificate's SAN.\n",
      "    197        \"\"\"\n",
      "    198        return self._identity\n",
      "    199\n",
      "    200    @property\n",
      "    201    def issuer(self) -> str:\n",
      "    202        \"\"\"\n",
      "    203        Returns a URL identifying this `IdentityToken`'s issuer.\n",
      "    204        \"\"\"\n",
      "    205        return self._iss\n",
      "    206\n",
      "    207    @property\n",
      "    208    def expected_certificate_subject(self) -> str:\n",
      "    209        \"\"\"\n",
      "    210        Returns a URL identifying the **expected** subject for any Sigstore\n",
      "    211        certificate issued against this identity token.\n",
      "    212\n",
      "    213        The behavior of this field is slightly subtle: for non-federated\n",
      "    214        identity providers (like a token issued directly by Google's IdP) it\n",
      "    215        should be exactly equivalent to `IdentityToken.issuer`. For federated\n",
      "    216        issuers (like Sigstore's own federated IdP) it should be equivalent to\n",
      "    217        the underlying federated issuer's URL, which is kept in an\n",
      "    218        implementation-defined claim.\n",
      "    219\n",
      "    220        This attribute exists so that clients who wish to inspect the expected\n",
      "    221        subject of their certificates can do so without relying on\n",
      "    222        implementation-specific behavior.\n",
      "    223        \"\"\"\n",
      "    224        if self._federated_issuer is not None:\n",
      "    225            return self._federated_issuer\n",
      "    226\n",
      "    227        return self.issuer\n",
      "    228\n",
      "    229    def __str__(self) -> str:\n",
      "    230        \"\"\"\n",
      "    231        Returns the underlying OIDC token for this identity.\n",
      "    232\n",
      "    233        That this token is secret in nature and **MUST NOT** be disclosed.\n",
      "    234        \"\"\"\n",
      "    235        return self._raw_token\n",
      "    \n",
      "\n",
      "An OIDC \"identity\", corresponding to an underlying OIDC token with a sensible\n",
      "subject, issuer, and audience for Sigstore purposes.\n",
      "\n",
      "IdentityToken(raw_token: str) View Source\n",
      "\n",
      "    \n",
      "    \n",
      "     82    def __init__(self, raw_token: str) -> None:\n",
      "     83        \"\"\"\n",
      "     84        Create a new `IdentityToken` from the given OIDC token.\n",
      "     85        \"\"\"\n",
      "     86\n",
      "     87        self._raw_token = raw_token\n",
      "     88\n",
      "     89        # NOTE: The lack of verification here is intentional, and is part of\n",
      "     90        # Sigstore's verification model: clients like sigstore-python are\n",
      "     91        # responsible only for forwarding the OIDC identity to Fulcio for\n",
      "     92        # certificate binding and issuance.\n",
      "     93        try:\n",
      "     94            self._unverified_claims = jwt.decode(\n",
      "     95                raw_token,\n",
      "     96                options={\n",
      "     97                    \"verify_signature\": False,\n",
      "     98                    \"verify_aud\": True,\n",
      "     99                    \"verify_iat\": True,\n",
      "    100                    \"verify_exp\": True,\n",
      "    101                    # These claims are required by OpenID Connect, so\n",
      "    102                    # we can strongly enforce their presence.\n",
      "    103                    # See: https://openid.net/specs/openid-connect-basic-1_0.html#IDToken\n",
      "    104                    \"require\": [\"aud\", \"sub\", \"iat\", \"exp\", \"iss\"],\n",
      "    105                },\n",
      "    106                audience=DEFAULT_AUDIENCE,\n",
      "    107                # NOTE: This leeway shouldn't be strictly necessary, but is\n",
      "    108                # included to preempt any (small) skew between the host\n",
      "    109                # and the originating IdP.\n",
      "    110                leeway=5,\n",
      "    111            )\n",
      "    112        except Exception as exc:\n",
      "    113            raise IdentityError(\n",
      "    114                \"Identity token is malformed or missing claims\"\n",
      "    115            ) from exc\n",
      "    116\n",
      "    117        self._iss: str = self._unverified_claims[\"iss\"]\n",
      "    118        self._nbf: int | None = self._unverified_claims.get(\"nbf\")\n",
      "    119        self._exp: int = self._unverified_claims[\"exp\"]\n",
      "    120\n",
      "    121        # Fail early if this token isn't within its validity period.\n",
      "    122        if not self.in_validity_period():\n",
      "    123            raise IdentityError(\"Identity token is not within its validity period\")\n",
      "    124\n",
      "    125        # When verifying the private key possession proof, Fulcio uses\n",
      "    126        # different claims depending on the token's issuer.\n",
      "    127        # We currently special-case a handful of these, and fall back\n",
      "    128        # on signing the \"sub\" claim otherwise.\n",
      "    129        identity_claim = _KNOWN_OIDC_ISSUERS.get(self.issuer)\n",
      "    130        if identity_claim is not None:\n",
      "    131            if identity_claim not in self._unverified_claims:\n",
      "    132                raise IdentityError(\n",
      "    133                    f\"Identity token is missing the required {identity_claim!r} claim\"\n",
      "    134                )\n",
      "    135\n",
      "    136            self._identity = str(self._unverified_claims.get(identity_claim))\n",
      "    137        else:\n",
      "    138            try:\n",
      "    139                self._identity = str(self._unverified_claims[\"sub\"])\n",
      "    140            except KeyError:\n",
      "    141                raise IdentityError(\n",
      "    142                    \"Identity token is missing the required 'sub' claim\"\n",
      "    143                )\n",
      "    144\n",
      "    145        # This identity token might have been retrieved directly from\n",
      "    146        # an identity provider, or it might be a \"federated\" identity token\n",
      "    147        # retrieved from a federated IdP (e.g., Sigstore's own Dex instance).\n",
      "    148        # In the latter case, the claims will also include a `federated_claims`\n",
      "    149        # set, which in turn should include a `connector_id` that reflects\n",
      "    150        # the \"real\" token issuer. We retrieve this, despite technically\n",
      "    151        # being an implementation detail, because it has value to client\n",
      "    152        # users: a client might want to make sure that its user is identifying\n",
      "    153        # with a *particular* IdP, which means that they need to pierce the\n",
      "    154        # federation layer to check which IdP is actually being used.\n",
      "    155        self._federated_issuer: str | None = None\n",
      "    156        federated_claims = self._unverified_claims.get(\"federated_claims\")\n",
      "    157        if federated_claims is not None:\n",
      "    158            if not isinstance(federated_claims, dict):\n",
      "    159                raise IdentityError(\n",
      "    160                    \"unexpected claim type: federated_claims is not a dict\"\n",
      "    161                )\n",
      "    162\n",
      "    163            federated_issuer = federated_claims.get(\"connector_id\")\n",
      "    164            if federated_issuer is not None:\n",
      "    165                if not isinstance(federated_issuer, str):\n",
      "    166                    raise IdentityError(\n",
      "    167                        \"unexpected claim type: federated_claims.connector_id is not a string\"\n",
      "    168                    )\n",
      "    169\n",
      "    170                self._federated_issuer = federated_issuer\n",
      "    \n",
      "\n",
      "Create a new `IdentityToken` from the given OIDC token.\n",
      "\n",
      "def in_validity_period(self) -> bool: View Source\n",
      "\n",
      "    \n",
      "    \n",
      "    172    def in_validity_period(self) -> bool:\n",
      "    173        \"\"\"\n",
      "    174        Returns whether or not this `Identity` is currently within its self-stated validity period.\n",
      "    175\n",
      "    176        NOTE: As noted in `Identity.__init__`, this is not a verifying wrapper;\n",
      "    177        the check here only asserts whether the *unverified* identity's claims\n",
      "    178        are within their validity period.\n",
      "    179        \"\"\"\n",
      "    180\n",
      "    181        now = datetime.now(timezone.utc).timestamp()\n",
      "    182\n",
      "    183        if self._nbf is not None:\n",
      "    184            return self._nbf <= now < self._exp\n",
      "    185        else:\n",
      "    186            return now < self._exp\n",
      "    \n",
      "\n",
      "Returns whether or not this `Identity` is currently within its self-stated\n",
      "validity period.\n",
      "\n",
      "NOTE: As noted in `Identity.__init__`, this is not a verifying wrapper; the\n",
      "check here only asserts whether the _unverified_ identity's claims are within\n",
      "their validity period.\n",
      "\n",
      "identity: str\n",
      "\n",
      "Returns this `IdentityToken`'s underlying \"subject\".\n",
      "\n",
      "Note that this is **not** always the `sub` claim in the corresponding identity\n",
      "token: depending onm the token's issuer, it may be a _different_ claim, such\n",
      "as `email`. This corresponds to the Sigstore ecosystem's behavior, e.g. in\n",
      "each issued certificate's SAN.\n",
      "\n",
      "issuer: str\n",
      "\n",
      "Returns a URL identifying this `IdentityToken`'s issuer.\n",
      "\n",
      "expected_certificate_subject: str\n",
      "\n",
      "Returns a URL identifying the **expected** subject for any Sigstore\n",
      "certificate issued against this identity token.\n",
      "\n",
      "The behavior of this field is slightly subtle: for non-federated identity\n",
      "providers (like a token issued directly by Google's IdP) it should be exactly\n",
      "equivalent to `IdentityToken.issuer`. For federated issuers (like Sigstore's\n",
      "own federated IdP) it should be equivalent to the underlying federated\n",
      "issuer's URL, which is kept in an implementation-defined claim.\n",
      "\n",
      "This attribute exists so that clients who wish to inspect the expected subject\n",
      "of their certificates can do so without relying on implementation-specific\n",
      "behavior.\n",
      "\n",
      "class IssuerError(builtins.Exception): View Source\n",
      "\n",
      "    \n",
      "    \n",
      "    238class IssuerError(Exception):\n",
      "    239    \"\"\"\n",
      "    240    Raised on any communication or format error with an OIDC issuer.\n",
      "    241    \"\"\"\n",
      "    242\n",
      "    243    pass\n",
      "    \n",
      "\n",
      "Raised on any communication or format error with an OIDC issuer.\n",
      "\n",
      "##### Inherited Members\n",
      "\n",
      "builtins.Exception\n",
      "\n",
      "    Exception\n",
      "\n",
      "builtins.BaseException\n",
      "\n",
      "    with_traceback\n",
      "    add_note\n",
      "    args\n",
      "\n",
      "class Issuer: View Source\n",
      "\n",
      "    \n",
      "    \n",
      "    246class Issuer:\n",
      "    247    \"\"\"\n",
      "    248    Represents an OIDC issuer (IdP).\n",
      "    249    \"\"\"\n",
      "    250\n",
      "    251    def __init__(self, base_url: str) -> None:\n",
      "    252        \"\"\"\n",
      "    253        Create a new `Issuer` from the given base URL.\n",
      "    254\n",
      "    255        This URL is used to locate an OpenID Connect configuration file,\n",
      "    256        which is then used to bootstrap the issuer's state (such\n",
      "    257        as authorization and token endpoints).\n",
      "    258        \"\"\"\n",
      "    259        oidc_config_url = urllib.parse.urljoin(\n",
      "    260            f\"{base_url}/\", \".well-known/openid-configuration\"\n",
      "    261        )\n",
      "    262\n",
      "    263        try:\n",
      "    264            resp: requests.Response = requests.get(oidc_config_url, timeout=30)\n",
      "    265        except (requests.ConnectionError, requests.Timeout) as exc:\n",
      "    266            raise NetworkError from exc\n",
      "    267\n",
      "    268        try:\n",
      "    269            resp.raise_for_status()\n",
      "    270        except requests.HTTPError as http_error:\n",
      "    271            raise IssuerError from http_error\n",
      "    272\n",
      "    273        try:\n",
      "    274            # We don't generally expect this to fail (since the provider should\n",
      "    275            # return a non-success HTTP code which we catch above), but we\n",
      "    276            # check just in case we have a misbehaving OIDC issuer.\n",
      "    277            self.oidc_config = _OpenIDConfiguration.model_validate(resp.json())\n",
      "    278        except ValueError as exc:\n",
      "    279            raise IssuerError(f\"OIDC issuer returned invalid configuration: {exc}\")\n",
      "    280\n",
      "    281    @classmethod\n",
      "    282    def production(cls) -> Issuer:\n",
      "    283        \"\"\"\n",
      "    284        Returns an `Issuer` configured against Sigstore's production-level services.\n",
      "    285        \"\"\"\n",
      "    286        return cls(DEFAULT_OAUTH_ISSUER_URL)\n",
      "    287\n",
      "    288    @classmethod\n",
      "    289    def staging(cls) -> Issuer:\n",
      "    290        \"\"\"\n",
      "    291        Returns an `Issuer` configured against Sigstore's staging-level services.\n",
      "    292        \"\"\"\n",
      "    293        return cls(STAGING_OAUTH_ISSUER_URL)\n",
      "    294\n",
      "    295    def identity_token(  # nosec: B107\n",
      "    296        self,\n",
      "    297        client_id: str = \"sigstore\",\n",
      "    298        client_secret: str = \"\",\n",
      "    299        force_oob: bool = False,\n",
      "    300    ) -> IdentityToken:\n",
      "    301        \"\"\"\n",
      "    302        Retrieves and returns an `IdentityToken` from the current `Issuer`, via OAuth.\n",
      "    303\n",
      "    304        This function blocks on user interaction.\n",
      "    305\n",
      "    306        The `force_oob` flag controls the kind of flow performed. When `False` (the default),\n",
      "    307        this function attempts to open the user's web browser before falling back to\n",
      "    308        an out-of-band flow. When `True`, the out-of-band flow is always used.\n",
      "    309        \"\"\"\n",
      "    310\n",
      "    311        # This function and the components that it relies on are based off of:\n",
      "    312        # https://github.com/psteniusubi/python-sample\n",
      "    313\n",
      "    314        from sigstore._internal.oidc.oauth import _OAuthFlow\n",
      "    315\n",
      "    316        code: str\n",
      "    317        with _OAuthFlow(client_id, client_secret, self) as server:\n",
      "    318            # Launch web browser\n",
      "    319            if not force_oob and webbrowser.open(server.base_uri):\n",
      "    320                print(\"Waiting for browser interaction...\", file=sys.stderr)\n",
      "    321            else:\n",
      "    322                server.enable_oob()\n",
      "    323                print(\n",
      "    324                    f\"Go to the following link in a browser:\\n\\n\\t{server.auth_endpoint}\",\n",
      "    325                    file=sys.stderr,\n",
      "    326                )\n",
      "    327\n",
      "    328            if not server.is_oob():\n",
      "    329                # Wait until the redirect server populates the response\n",
      "    330                while server.auth_response is None:\n",
      "    331                    time.sleep(0.1)\n",
      "    332\n",
      "    333                auth_error = server.auth_response.get(\"error\")\n",
      "    334                if auth_error is not None:\n",
      "    335                    raise IdentityError(\n",
      "    336                        f\"Error response from auth endpoint: {auth_error[0]}\"\n",
      "    337                    )\n",
      "    338                code = server.auth_response[\"code\"][0]\n",
      "    339            else:\n",
      "    340                # In the out-of-band case, we wait until the user provides the code\n",
      "    341                code = input(\"Enter verification code: \")\n",
      "    342\n",
      "    343        # Provide code to token endpoint\n",
      "    344        data = {\n",
      "    345            \"grant_type\": \"authorization_code\",\n",
      "    346            \"redirect_uri\": server.redirect_uri,\n",
      "    347            \"code\": code,\n",
      "    348            \"code_verifier\": server.oauth_session.code_verifier,\n",
      "    349        }\n",
      "    350        auth = (\n",
      "    351            client_id,\n",
      "    352            client_secret,\n",
      "    353        )\n",
      "    354        logging.debug(f\"PAYLOAD: data={data}\")\n",
      "    355        try:\n",
      "    356            resp: requests.Response = requests.post(\n",
      "    357                self.oidc_config.token_endpoint,\n",
      "    358                data=data,\n",
      "    359                auth=auth,\n",
      "    360                timeout=30,\n",
      "    361            )\n",
      "    362        except (requests.ConnectionError, requests.Timeout) as exc:\n",
      "    363            raise NetworkError from exc\n",
      "    364\n",
      "    365        try:\n",
      "    366            resp.raise_for_status()\n",
      "    367        except requests.HTTPError as http_error:\n",
      "    368            raise IdentityError(\n",
      "    369                f\"Token request failed with {resp.status_code}\"\n",
      "    370            ) from http_error\n",
      "    371\n",
      "    372        token_json = resp.json()\n",
      "    373        token_error = token_json.get(\"error\")\n",
      "    374        if token_error is not None:\n",
      "    375            raise IdentityError(f\"Error response from token endpoint: {token_error}\")\n",
      "    376\n",
      "    377        return IdentityToken(token_json[\"access_token\"])\n",
      "    \n",
      "\n",
      "Represents an OIDC issuer (IdP).\n",
      "\n",
      "Issuer(base_url: str) View Source\n",
      "\n",
      "    \n",
      "    \n",
      "    251    def __init__(self, base_url: str) -> None:\n",
      "    252        \"\"\"\n",
      "    253        Create a new `Issuer` from the given base URL.\n",
      "    254\n",
      "    255        This URL is used to locate an OpenID Connect configuration file,\n",
      "    256        which is then used to bootstrap the issuer's state (such\n",
      "    257        as authorization and token endpoints).\n",
      "    258        \"\"\"\n",
      "    259        oidc_config_url = urllib.parse.urljoin(\n",
      "    260            f\"{base_url}/\", \".well-known/openid-configuration\"\n",
      "    261        )\n",
      "    262\n",
      "    263        try:\n",
      "    264            resp: requests.Response = requests.get(oidc_config_url, timeout=30)\n",
      "    265        except (requests.ConnectionError, requests.Timeout) as exc:\n",
      "    266            raise NetworkError from exc\n",
      "    267\n",
      "    268        try:\n",
      "    269            resp.raise_for_status()\n",
      "    270        except requests.HTTPError as http_error:\n",
      "    271            raise IssuerError from http_error\n",
      "    272\n",
      "    273        try:\n",
      "    274            # We don't generally expect this to fail (since the provider should\n",
      "    275            # return a non-success HTTP code which we catch above), but we\n",
      "    276            # check just in case we have a misbehaving OIDC issuer.\n",
      "    277            self.oidc_config = _OpenIDConfiguration.model_validate(resp.json())\n",
      "    278        except ValueError as exc:\n",
      "    279            raise IssuerError(f\"OIDC issuer returned invalid configuration: {exc}\")\n",
      "    \n",
      "\n",
      "Create a new `Issuer` from the given base URL.\n",
      "\n",
      "This URL is used to locate an OpenID Connect configuration file, which is then\n",
      "used to bootstrap the issuer's state (such as authorization and token\n",
      "endpoints).\n",
      "\n",
      "@classmethod\n",
      "\n",
      "def production(cls) -> Issuer: View Source\n",
      "\n",
      "    \n",
      "    \n",
      "    281    @classmethod\n",
      "    282    def production(cls) -> Issuer:\n",
      "    283        \"\"\"\n",
      "    284        Returns an `Issuer` configured against Sigstore's production-level services.\n",
      "    285        \"\"\"\n",
      "    286        return cls(DEFAULT_OAUTH_ISSUER_URL)\n",
      "    \n",
      "\n",
      "Returns an `Issuer` configured against Sigstore's production-level services.\n",
      "\n",
      "@classmethod\n",
      "\n",
      "def staging(cls) -> Issuer: View Source\n",
      "\n",
      "    \n",
      "    \n",
      "    288    @classmethod\n",
      "    289    def staging(cls) -> Issuer:\n",
      "    290        \"\"\"\n",
      "    291        Returns an `Issuer` configured against Sigstore's staging-level services.\n",
      "    292        \"\"\"\n",
      "    293        return cls(STAGING_OAUTH_ISSUER_URL)\n",
      "    \n",
      "\n",
      "Returns an `Issuer` configured against Sigstore's staging-level services.\n",
      "\n",
      "def identity_token( self, client_id: str = 'sigstore', client_secret: str =\n",
      "'', force_oob: bool = False) -> IdentityToken: View Source\n",
      "\n",
      "    \n",
      "    \n",
      "    295    def identity_token(  # nosec: B107\n",
      "    296        self,\n",
      "    297        client_id: str = \"sigstore\",\n",
      "    298        client_secret: str = \"\",\n",
      "    299        force_oob: bool = False,\n",
      "    300    ) -> IdentityToken:\n",
      "    301        \"\"\"\n",
      "    302        Retrieves and returns an `IdentityToken` from the current `Issuer`, via OAuth.\n",
      "    303\n",
      "    304        This function blocks on user interaction.\n",
      "    305\n",
      "    306        The `force_oob` flag controls the kind of flow performed. When `False` (the default),\n",
      "    307        this function attempts to open the user's web browser before falling back to\n",
      "    308        an out-of-band flow. When `True`, the out-of-band flow is always used.\n",
      "    309        \"\"\"\n",
      "    310\n",
      "    311        # This function and the components that it relies on are based off of:\n",
      "    312        # https://github.com/psteniusubi/python-sample\n",
      "    313\n",
      "    314        from sigstore._internal.oidc.oauth import _OAuthFlow\n",
      "    315\n",
      "    316        code: str\n",
      "    317        with _OAuthFlow(client_id, client_secret, self) as server:\n",
      "    318            # Launch web browser\n",
      "    319            if not force_oob and webbrowser.open(server.base_uri):\n",
      "    320                print(\"Waiting for browser interaction...\", file=sys.stderr)\n",
      "    321            else:\n",
      "    322                server.enable_oob()\n",
      "    323                print(\n",
      "    324                    f\"Go to the following link in a browser:\\n\\n\\t{server.auth_endpoint}\",\n",
      "    325                    file=sys.stderr,\n",
      "    326                )\n",
      "    327\n",
      "    328            if not server.is_oob():\n",
      "    329                # Wait until the redirect server populates the response\n",
      "    330                while server.auth_response is None:\n",
      "    331                    time.sleep(0.1)\n",
      "    332\n",
      "    333                auth_error = server.auth_response.get(\"error\")\n",
      "    334                if auth_error is not None:\n",
      "    335                    raise IdentityError(\n",
      "    336                        f\"Error response from auth endpoint: {auth_error[0]}\"\n",
      "    337                    )\n",
      "    338                code = server.auth_response[\"code\"][0]\n",
      "    339            else:\n",
      "    340                # In the out-of-band case, we wait until the user provides the code\n",
      "    341                code = input(\"Enter verification code: \")\n",
      "    342\n",
      "    343        # Provide code to token endpoint\n",
      "    344        data = {\n",
      "    345            \"grant_type\": \"authorization_code\",\n",
      "    346            \"redirect_uri\": server.redirect_uri,\n",
      "    347            \"code\": code,\n",
      "    348            \"code_verifier\": server.oauth_session.code_verifier,\n",
      "    349        }\n",
      "    350        auth = (\n",
      "    351            client_id,\n",
      "    352            client_secret,\n",
      "    353        )\n",
      "    354        logging.debug(f\"PAYLOAD: data={data}\")\n",
      "    355        try:\n",
      "    356            resp: requests.Response = requests.post(\n",
      "    357                self.oidc_config.token_endpoint,\n",
      "    358                data=data,\n",
      "    359                auth=auth,\n",
      "    360                timeout=30,\n",
      "    361            )\n",
      "    362        except (requests.ConnectionError, requests.Timeout) as exc:\n",
      "    363            raise NetworkError from exc\n",
      "    364\n",
      "    365        try:\n",
      "    366            resp.raise_for_status()\n",
      "    367        except requests.HTTPError as http_error:\n",
      "    368            raise IdentityError(\n",
      "    369                f\"Token request failed with {resp.status_code}\"\n",
      "    370            ) from http_error\n",
      "    371\n",
      "    372        token_json = resp.json()\n",
      "    373        token_error = token_json.get(\"error\")\n",
      "    374        if token_error is not None:\n",
      "    375            raise IdentityError(f\"Error response from token endpoint: {token_error}\")\n",
      "    376\n",
      "    377        return IdentityToken(token_json[\"access_token\"])\n",
      "    \n",
      "\n",
      "Retrieves and returns an `IdentityToken` from the current `Issuer`, via OAuth.\n",
      "\n",
      "This function blocks on user interaction.\n",
      "\n",
      "The `force_oob` flag controls the kind of flow performed. When `False` (the\n",
      "default), this function attempts to open the user's web browser before falling\n",
      "back to an out-of-band flow. When `True`, the out-of-band flow is always used.\n",
      "\n",
      "class IdentityError([sigstore.errors.Error](errors.html#Error)): View Source\n",
      "\n",
      "    \n",
      "    \n",
      "    380class IdentityError(Error):\n",
      "    381    \"\"\"\n",
      "    382    Wraps `id`'s IdentityError.\n",
      "    383    \"\"\"\n",
      "    384\n",
      "    385    @classmethod\n",
      "    386    def raise_from_id(cls, exc: id.IdentityError) -> NoReturn:\n",
      "    387        \"\"\"Raises a wrapped IdentityError from the provided `id.IdentityError`.\"\"\"\n",
      "    388        raise cls(str(exc)) from exc\n",
      "    389\n",
      "    390    def diagnostics(self) -> str:\n",
      "    391        \"\"\"Returns diagnostics for the error.\"\"\"\n",
      "    392        if isinstance(self.__cause__, id.GitHubOidcPermissionCredentialError):\n",
      "    393            return f\"\"\"\n",
      "    394                Insufficient permissions for GitHub Actions workflow.\n",
      "    395\n",
      "    396                The most common reason for this is incorrect\n",
      "    397                configuration of the top-level `permissions` setting of the\n",
      "    398                workflow YAML file. It should be configured like so:\n",
      "    399\n",
      "    400                    permissions:\n",
      "    401                      id-token: write\n",
      "    402\n",
      "    403                Relevant documentation here:\n",
      "    404\n",
      "    405                    https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect#adding-permissions-settings\n",
      "    406\n",
      "    407                Another possible reason is that the workflow run has been\n",
      "    408                triggered by a PR from a forked repository. PRs from forked\n",
      "    409                repositories typically cannot be granted write access.\n",
      "    410\n",
      "    411                Relevant documentation here:\n",
      "    412\n",
      "    413                    https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token\n",
      "    414\n",
      "    415                Additional context:\n",
      "    416\n",
      "    417                {self.__cause__}\n",
      "    418                \"\"\"\n",
      "    419        else:\n",
      "    420            return f\"\"\"\n",
      "    421                An issue occurred with ambient credential detection.\n",
      "    422\n",
      "    423                Additional context:\n",
      "    424\n",
      "    425                {self}\n",
      "    426            \"\"\"\n",
      "    \n",
      "\n",
      "Wraps `id`'s IdentityError.\n",
      "\n",
      "@classmethod\n",
      "\n",
      "def raise_from_id(cls, exc: id.IdentityError) -> NoReturn: View Source\n",
      "\n",
      "    \n",
      "    \n",
      "    385    @classmethod\n",
      "    386    def raise_from_id(cls, exc: id.IdentityError) -> NoReturn:\n",
      "    387        \"\"\"Raises a wrapped IdentityError from the provided `id.IdentityError`.\"\"\"\n",
      "    388        raise cls(str(exc)) from exc\n",
      "    \n",
      "\n",
      "Raises a wrapped IdentityError from the provided `id.IdentityError`.\n",
      "\n",
      "def diagnostics(self) -> str: View Source\n",
      "\n",
      "    \n",
      "    \n",
      "    390    def diagnostics(self) -> str:\n",
      "    391        \"\"\"Returns diagnostics for the error.\"\"\"\n",
      "    392        if isinstance(self.__cause__, id.GitHubOidcPermissionCredentialError):\n",
      "    393            return f\"\"\"\n",
      "    394                Insufficient permissions for GitHub Actions workflow.\n",
      "    395\n",
      "    396                The most common reason for this is incorrect\n",
      "    397                configuration of the top-level `permissions` setting of the\n",
      "    398                workflow YAML file. It should be configured like so:\n",
      "    399\n",
      "    400                    permissions:\n",
      "    401                      id-token: write\n",
      "    402\n",
      "    403                Relevant documentation here:\n",
      "    404\n",
      "    405                    https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect#adding-permissions-settings\n",
      "    406\n",
      "    407                Another possible reason is that the workflow run has been\n",
      "    408                triggered by a PR from a forked repository. PRs from forked\n",
      "    409                repositories typically cannot be granted write access.\n",
      "    410\n",
      "    411                Relevant documentation here:\n",
      "    412\n",
      "    413                    https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token\n",
      "    414\n",
      "    415                Additional context:\n",
      "    416\n",
      "    417                {self.__cause__}\n",
      "    418                \"\"\"\n",
      "    419        else:\n",
      "    420            return f\"\"\"\n",
      "    421                An issue occurred with ambient credential detection.\n",
      "    422\n",
      "    423                Additional context:\n",
      "    424\n",
      "    425                {self}\n",
      "    426            \"\"\"\n",
      "    \n",
      "\n",
      "Returns diagnostics for the error.\n",
      "\n",
      "##### Inherited Members\n",
      "\n",
      "builtins.Exception\n",
      "\n",
      "    Exception\n",
      "\n",
      "[sigstore.errors.Error](errors.html#Error)\n",
      "\n",
      "    [print_and_exit](errors.html#Error.print_and_exit)\n",
      "\n",
      "builtins.BaseException\n",
      "\n",
      "    with_traceback\n",
      "    add_note\n",
      "    args\n",
      "\n",
      "def detect_credential() -> Optional[str]: View Source\n",
      "\n",
      "    \n",
      "    \n",
      "    429def detect_credential() -> Optional[str]:\n",
      "    430    \"\"\"Calls `id.detect_credential`, but wraps exceptions with our own exception type.\"\"\"\n",
      "    431    try:\n",
      "    432        return cast(Optional[str], id.detect_credential(_DEFAULT_AUDIENCE))\n",
      "    433    except id.IdentityError as exc:\n",
      "    434        IdentityError.raise_from_id(exc)\n",
      "    \n",
      "\n",
      "Calls `id.detect_credential`, but wraps exceptions with our own exception\n",
      "type.\n",
      "\n",
      "\n"
     ]
    }
   ],
   "source": [
    "# Print the first 2 markdowns\n",
    "count = 0\n",
    "for key, value in data.items():\n",
    "    print(f\"Markdown for '{key}':\")\n",
    "    print(value)\n",
    "    count += 1\n",
    "    if count == 2:\n",
    "        break"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "be6cabfa-8414-45ea-a030-bd963e5434b1",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Downloaded content for errors.py in errors\n",
      "Downloaded content for oidc.py in oidc\n",
      "Downloaded content for sign.py in sign\n",
      "Downloaded content for transparency.py in transparency\n",
      "Downloaded content for verify/models.py in verify_models\n",
      "Downloaded content for verify/policy.py in verify_policy\n",
      "Downloaded content for verify/verifier.py in verify_verifier\n",
      "Nested JSON data created and stored in nested_data.json\n"
     ]
    }
   ],
   "source": [
    "def download_file(url):\n",
    "    response = requests.get(url)\n",
    "    if response.status_code == 200:\n",
    "        return response.text\n",
    "    return None\n",
    "\n",
    "base_url = \"https://raw.githubusercontent.com/sigstore/sigstore-python/main/sigstore/\"\n",
    "files = {\n",
    "    \"errors\": \"errors.py\",\n",
    "    \"oidc\": \"oidc.py\",\n",
    "    \"sign\": \"sign.py\",\n",
    "    \"transparency\": \"transparency.py\",\n",
    "    \"verify_models\": \"verify/models.py\",\n",
    "    \"verify_policy\": \"verify/policy.py\",\n",
    "    \"verify_verifier\": \"verify/verifier.py\"\n",
    "}\n",
    "\n",
    "data = {}\n",
    "\n",
    "for key, file_path in files.items():\n",
    "    file_url = f\"{base_url}/{file_path}\"  # Corrected URL formation\n",
    "    file_content = download_file(file_url)\n",
    "    if file_content:\n",
    "        print(f\"Downloaded content for {file_path} in {key}\")\n",
    "        data[key] = {\n",
    "            \"markdown\": \"\",  # Placeholder for markdown content (to be added later)\n",
    "            \"code\": [{file_path: file_content}]  # List to store code content\n",
    "        }\n",
    "    else:\n",
    "        print(f\"Failed to download content for {file_path} in {key}\")\n",
    "\n",
    "with open('../../data/raw/markdown_data.json', 'r') as json_file:\n",
    "    existing_data = json.load(json_file)\n",
    "\n",
    "for key, value in existing_data.items():\n",
    "    if key in data:\n",
    "        data[key][\"markdown\"] = re.sub(r'^\\s*\\d.*\\n?', '', value, flags=re.MULTILINE)\n",
    "\n",
    "with open('../../data/raw/nested_data.json', 'w') as json_file:\n",
    "    json.dump(data, json_file, indent=4)\n",
    "\n",
    "print(\"Nested JSON data created and stored in nested_data.json\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
